/* DO NOT EDIT */
/**
 * Auto-generated TypeScript types from application-v1.json schema
 *
 * This file is generated by scripts/generate-app-types.mjs
 * DO NOT MANUALLY EDIT - your changes will be overwritten on next build
 */

/**
 * Page configuration
 */
export interface PageConfig {
  /** Page title */
  title?: string;
  /** Page description */
  description?: string;
  /** Page content: array of widgets or containers */
  content: ContentItem[];
  /** Page-level skin (name or token overrides). Overrides site-level skin. */
  skin?: string | Record<string, unknown>;
  /** Per-page translations keyed by language code */
  translations?: Record<string, Record<string, string>>;
  /** Page tags */
  tags?: string[];
}

/**
 * Widget (leaf component)
 */
export interface WidgetConfig {
  /** Widget type (component registry key) */
  type: string;
  /** Widget props (arbitrary schema per widget) */
  props?: Record<string, unknown>;
  /** Widget-level skin (name or token overrides). Overrides page/site skin. */
  skin?: string | Record<string, unknown>;
}

/**
 * Container (grouping element with layout and optional children). Supports unlimited nesting.
 */
export interface ContainerConfig {
  /** Container type marker */
  type: "container";
  /** Layout type (grid, flex, stack, etc.) */
  layout?: string;
  /** Container props (layout configuration) */
  props?: Record<string, unknown>;
  /** Child widgets or containers (recursive, unlimited nesting depth) */
  children?: ContentItem[];
  /** Container-level skin (name or token overrides). Overrides page/site skin. */
  skin?: string | Record<string, unknown>;
}

/**
 * ContentItem — union type: either Widget or Container
 */
export type ContentItem = WidgetConfig | ContainerConfig;

/**
 * SEO metadata and site identity
 */
export interface SEOConfig {
  /** Site title */
  title: string;
  /** Site meta description */
  description?: string;
  /** Site author name */
  author?: string;
  /** Site author URL */
  author_url?: string;
  /** SEO keywords */
  keywords?: string[];
  /** Open Graph image URL */
  og_image?: string;
}

/**
 * Theme configuration
 */
export interface ThemesConfig {
  /** Default theme name */
  default: string;
  /** Global theme keys to include */
  globals?: string[];
  /** Custom theme definitions */
  custom?: Record<string, Record<string, unknown>>;
}

export interface CustomThemeDefinition {
  /** Theme name */
  name: string;
  /** Theme description */
  description?: string;
  /** Light mode tokens */
  light: Record<string, unknown>;
  /** Dark mode tokens */
  dark: Record<string, unknown>;
}

/**
 * YAML configuration schema for Fachada v1.x applications (application.yaml)
 */
export interface ApplicationConfig {
  /** SEO metadata and site identity */
  seo: SEOConfig;
  /** Theme configuration */
  themes: ThemesConfig;
  /** Page definitions keyed by page ID */
  pages: Record<string, PageConfig>;
  /** Global skin definitions (CSS token overrides) keyed by skin name */
  skins?: Record<string, Record<string, unknown>>;
  /** Asset references (images, files) keyed by logical name */
  assets?: Record<string, string | Record<string, string>>;
  /** Site navigation tree structure */
  siteTree?: Record<string, unknown>;
}
