/**
 * Theme configuration — single source of truth for all visual theme definitions.
 *
 * THEME_DEFINITIONS are defined in src/skin/defaults/index.ts, generated from skin theme files during build.
 * This file provides types and utilities only; theme content is generated by scripts/generate-themes.mjs.
 */

export type ThemeStyle = string;
export type ColorMode = "light" | "dark" | "auto";

export interface ThemeTokens {
  bgPrimary: string;
  bgSecondary: string;
  textPrimary: string;
  textSecondary: string;
  accent: string;
  accentHover: string;
  accentSecondary?: string | null;
  accentTertiary?: string | null;
  border: string;
  shadow: string;
  borderRadius: string;
  transition: string;
  glow: string;
  gradient: string;
  spacingSection: string;
  spacingCard: string;
  spacingElement: string;
  /** Font family for body text */
  fontBody: string;
  /** Font family for headings */
  fontHeading: string;
  /** Monospace font family */
  fontMono: string;
  /** Font weight for headings */
  headingWeight: string;
  /** Line-height for body text */
  bodyLineHeight: string;
  /** Max content width for the main container */
  contentMaxWidth: string;
  /** Letter-spacing for headings */
  headingLetterSpacing: string;
  /** Button text color on gradient backgrounds */
  buttonTextColor: string;
  /** Button text shadow for readability */
  buttonTextShadow: string;
  /** Scanline opacity for decorative effects */
  scanlineOpacity: string;
}

export interface ThemeDefinition {
  name: string;
  description: string;
  light: ThemeTokens;
  dark: ThemeTokens;
}

/** Maps ThemeTokens keys to CSS custom property names. */
export const CSS_VAR_MAP: Record<keyof ThemeTokens, string> = {
  bgPrimary: "--bg-primary",
  bgSecondary: "--bg-secondary",
  textPrimary: "--text-primary",
  textSecondary: "--text-secondary",
  accent: "--accent",
  accentHover: "--accent-hover",
  accentSecondary: "--accent-secondary",
  accentTertiary: "--accent-tertiary",
  border: "--border",
  shadow: "--shadow",
  borderRadius: "--border-radius",
  transition: "--transition",
  glow: "--glow",
  gradient: "--gradient",
  spacingSection: "--spacing-section",
  spacingCard: "--spacing-card",
  spacingElement: "--spacing-element",
  fontBody: "--font-body",
  fontHeading: "--font-heading",
  fontMono: "--font-mono",
  headingWeight: "--heading-weight",
  bodyLineHeight: "--body-line-height",
  contentMaxWidth: "--content-max-width",
  headingLetterSpacing: "--heading-letter-spacing",
  buttonTextColor: "--button-text-color",
  buttonTextShadow: "--button-text-shadow",
  scanlineOpacity: "--scanline-opacity",
};

// Import auto-generated theme definitions from skin theme sources → TypeScript build chain
import { DEFAULT_SKINS } from "../skin/defaults";
export const THEME_DEFINITIONS: Record<ThemeStyle, ThemeDefinition> =
  DEFAULT_SKINS;

export const THEME_STYLES = Object.keys(THEME_DEFINITIONS) as ThemeStyle[];

/** Returns the active token set for a given style and effective color mode. */
export function getActiveTokens(
  styleTheme: ThemeStyle,
  effectiveColorMode: "light" | "dark",
): ThemeTokens {
  return THEME_DEFINITIONS[styleTheme][effectiveColorMode];
}
